#!/usr/bin/env bash
#
# make-page.sh
#
# Automates the "commit to WordPress" half of the jq-to-WP-page workflow
# (Steps 4-8 in howto-jq-to-wp-page.md). You still design and benchtest
# the query/logic yourself first (jq + wp eval) -- this script just
# takes your PROVEN php payload and wires it up as a real page:
# writes the file into the theme, fixes host permissions, validates
# syntax, and registers the page if it doesn't already exist.
#
# Usage:
#   bash make-page.sh <slug> "<Page Title>" <path-to-php-payload-file>
#
# Example:
#   bash make-page.sh recurring "Regular Events" recurring-payload.php
#
# Where recurring-payload.php contains ONLY the content that goes
# between get_header() and get_footer() -- this script wraps it for you.
#
set -euo pipefail

CONTAINER="oswp-wordpress-1"
THEME_DIR="wp-content/themes/oswp-child"

if [ "$#" -ne 3 ]; then
    echo "Usage: bash make-page.sh <slug> \"<Page Title>\" <path-to-php-payload-file>" >&2
    exit 1
fi

SLUG="$1"
TITLE="$2"
PAYLOAD_FILE="$3"
TEMPLATE_FILE="${THEME_DIR}/page-${SLUG}.php"

if [ ! -d "$THEME_DIR" ]; then
    echo "ERROR: $THEME_DIR not found. Run this from ~/oswp." >&2
    exit 1
fi

if [ ! -f "$PAYLOAD_FILE" ]; then
    echo "ERROR: payload file '$PAYLOAD_FILE' not found." >&2
    exit 1
fi

echo "==> Building $TEMPLATE_FILE from $PAYLOAD_FILE ..."

# Wrap the payload with get_header()/get_footer() and write it into
# the container via docker exec -- NOT saved as a local file first,
# avoiding the paste-vs-run mistake documented in the how-to.
{
    echo "<?php"
    echo "/**"
    echo " * Template: page-${SLUG}.php"
    echo " * Generated by make-page.sh -- payload from ${PAYLOAD_FILE}"
    echo " */"
    echo "get_header();"
    echo "?>"
    cat "$PAYLOAD_FILE"
    echo "<?php get_footer(); ?>"
} | docker exec -i "$CONTAINER" bash -c "cat > /var/www/html/${TEMPLATE_FILE}"

echo "==> Fixing host-side file ownership ..."
sudo chown simon:simon "$TEMPLATE_FILE" 2>/dev/null || \
    echo "    (skipped -- sudo not available or not needed here)"

echo "==> Validating PHP syntax ..."
docker exec -i "$CONTAINER" php -l "/var/www/html/${TEMPLATE_FILE}"

echo "==> Checking whether the '${SLUG}' page already exists ..."
EXISTING_ID=$(docker exec -i "$CONTAINER" wp post list \
    --post_type=page \
    --name="$SLUG" \
    --field=ID \
    --allow-root 2>/dev/null || true)

if [ -n "$EXISTING_ID" ]; then
    echo "==> Page already exists (ID: $EXISTING_ID) -- skipping creation."
else
    echo "==> Creating page '${TITLE}' (slug: ${SLUG}) ..."
    docker exec -i "$CONTAINER" wp post create \
        --post_type=page \
        --post_title="$TITLE" \
        --post_name="$SLUG" \
        --post_status=publish \
        --allow-root
fi

echo "==> Done. View at: http://localhost:8080/${SLUG}/"
